/**
 * Clean Protobuf Enum Imports
 * Generated from actual protobuf definitions
 * This file is auto-generated from the protobuf file
 * 
 * Generated from: E:\Zera Github\zera-js-sdk\proto\generated\txn_pb.js
 * 
 * To regenerate this file when protobuf definitions change:
 * 1. Update the .proto files
 * 2. Run: node proto/build.js
 */

// These enum values are extracted from the actual generated protobuf file
// They represent the real protobuf definitions, not copies

export const TRANSACTION_TYPE = {
  "COIN_TYPE": 0,
  "FOUNDATION_TYPE": 2,
  "MINT_TYPE": 1,
  "ITEM_MINT_TYPE": 3,
  "CONTRACT_TXN_TYPE": 4,
  "VOTE_TYPE": 5,
  "PROPOSAL_TYPE": 6,
  "SMART_CONTRACT_TYPE": 7,
  "SMART_CONTRACT_EXECUTE_TYPE": 8,
  "SELF_CURRENCY_EQUIV_TYPE": 9,
  "AUTHORIZED_CURRENCY_EQUIV_TYPE": 10,
  "EXPENSE_RATIO_TYPE": 11,
  "NFT_TYPE": 12,
  "UPDATE_CONTRACT_TYPE": 13,
  "VALIDATOR_REGISTRATION_TYPE": 14,
  "VALIDATOR_HEARTBEAT_TYPE": 15,
  "PROPOSAL_RESULT_TYPE": 16,
  "DELEGATED_VOTING_TYPE": 17,
  "REVOKE_TYPE": 18,
  "QUASH_TYPE": 19,
  "FAST_QUORUM_TYPE": 20,
  "COMPLIANCE_TYPE": 21,
  "SBT_BURN_TYPE": 22,
  "REQUIRED_VERSION": 23,
  "SMART_CONTRACT_INSTANTIATE_TYPE": 24,
  "UKNOWN_TYPE": 25,
  "ALLOWANCE_TYPE": 26
};

export const CONTRACT_FEE_TYPE = {
  "FIXED": 0,
  "CUR_EQUIVALENT": 1,
  "PERCENTAGE": 2,
  "NONE": 3
};

export const TXN_STATUS = {
  "OK": 0,
  "INVALID_PARAMETERS": 1,
  "INSUFFICIENT_AMOUNT": 2,
  "INSUFFICIENT_CONTRACT_FEES": 3,
  "AUTHORIZED_INSUFFICIENT_FEES": 4,
  "AUTHORIZED_INSUFFICIENT_CONTRACT_FEES": 5,
  "INVALID_CONTRACT": 6,
  "INVALID_AUTH_KEY": 7,
  "INVALID_WALLET_ADDRESS": 8,
  "INVALID_MULTI_TRANSACTION": 9,
  "INVALID_CONTRACT_PARAMETERS": 10,
  "INVALID_CONTRACT_FEE_ID": 11,
  "INVALID_UINT256": 12,
  "EXCEEDED_MAX_SUPPLY": 13,
  "INVALID_NFT": 14,
  "NFT_OWNERSHIP": 15,
  "VALIDATOR_ADDRESS": 16,
  "CONTRACT_HAS_NO_GOVERNANCE": 17,
  "INVALID_BASE_FEE_ID": 18,
  "EXPENSE_RATIO_DUPLICATE": 19,
  "RESTRICTED_SYMBOL": 20,
  "INVALID_PROPOSAL_ID": 21,
  "PROPOSAL_NOT_IN_VOTING_PERIOD": 22,
  "TIME_DELAY_INITIALIZED": 23,
  "INVALID_TXN_HASH": 24,
  "INVALID_TXN_TYPE": 25,
  "TIME_DELAY_EXPIRED": 26,
  "DUPLICATE_AUTH_KEY": 27,
  "KEY_WEIGHT_TOO_LOW": 28,
  "INVALID_ITEM": 29,
  "INVALID_PROPOSAL": 30,
  "PROPOSAL_DOES_NOT_BELONG_TO_SENDER": 31,
  "INVALID_ADDRESS": 32,
  "NO_CHANGE_TO_COMPLIANCE": 33,
  "COMPLIANCE_CHECK_FAILED": 34,
  "INVALID_SAFE_SEND": 35,
  "INVALID_TXN_DATA": 36,
  "DUPLICATE_SMART_CONTRACT_NONCE": 37,
  "INVALID_SMART_CONTRACT": 38,
  "FAULTY_TXN": 39,
  "OUT_OF_GAS": 40,
  "INVALID_ALLOWANCE": 41
};

export const GOVERNANCE_TYPE = {
  "STAGED": 0,
  "CYCLE": 1,
  "STAGGERED": 2,
  "ADAPTIVE": 3,
  "REMOVE": 4
};

export const CONTRACT_TYPE = {
  "TOKEN": 0,
  "NFT": 1,
  "SBT": 2
};

export const LANGUAGE = {
  "COMPILED": 0,
  "PYTHON": 1,
  "JAVASCRIPT": 2
};

export const PROPOSAL_PERIOD = {
  "DAYS": 0,
  "MONTHS": 1
};

export const VARIABLE_TYPE = {
  "INT": 0,
  "SHORT": 1,
  "LONG": 2,
  "LONG_LONG": 3,
  "BOOL": 4,
  "STRING": 5
};

// Export all enums as a single object for convenience
export const PROTOBUF_ENUMS = {
  TRANSACTION_TYPE,
  CONTRACT_FEE_TYPE,
  TXN_STATUS,
  GOVERNANCE_TYPE,
  CONTRACT_TYPE,
  LANGUAGE,
  PROPOSAL_PERIOD,
  VARIABLE_TYPE
};

export default PROTOBUF_ENUMS;
